export const ANIME_ACRONYMS = {
  // Shonen / Action
  'SNK': 'Shingeki no Kyojin',
  'AOT': 'Shingeki no Kyojin',
  'JJK': 'Jujutsu Kaisen',
  'MHA': 'Boku no Hero Academia',
  'BNHA': 'Boku no Hero Academia',
  'FMA': 'Fullmetal Alchemist',
  'FMAB': 'Fullmetal Alchemist Brotherhood',
  'HXH': 'Hunter x Hunter',
  'KNY': 'Kimetsu no Yaiba',
  'DS': 'Demon Slayer',
  'OPM': 'One Punch Man',
  'OP': 'One Piece',
  'DB': 'Dragon Ball',
  'DBZ': 'Dragon Ball Z',
  'DBS': 'Dragon Ball Super',
  'BC': 'Black Clover',
  'NNT': 'Nanatsu no Taizai',
  'SDS': 'Nanatsu no Taizai',
  'TPN': 'Yakusoku no Neverland',
  'CSM': 'Chainsaw Man',
  'BL': 'Blue Lock',
  'SPY': 'Spy x Family',
  'SXF': 'Spy x Family',
  'MP100': 'Mob Psycho 100',
  'TG': 'Tokyo Ghoul',
  'SAO': 'Sword Art Online',
  'VS': 'Vinland Saga',
  'NGE': 'Neon Genesis Evangelion',
  'TTGL': 'Tengen Toppa Gurren Lagann',
  'NGNL': 'No Game No Life',
  'YYH': 'Yu Yu Hakusho',
  'GTO': 'Great Teacher Onizuka',
  'FLCL': 'FLCL',
  'LOTGH': 'Legend of the Galactic Heroes',
  // Isekai / Fantasy
  'KS': 'Konosuba',
  'RE0': 'Re:Zero',
  'RZ': 'Re:Zero',
  'TRZ': 'Tate no Yuusha no Nariagari',
  'STB': 'Sword Art Online',
  'RI': 'Tensei shitara Slime Datta Ken',
  'TSTS': 'Tensei shitara Slime Datta Ken',
  // Romance / Slice of life
  'YOI': 'Yuri on Ice',
  'AHR': 'Ao Haru Ride',
  'SK8': 'SK8 the Infinity',
  'YLS': 'Yahari Ore no Seishun Love Comedy wa Machigatteiru',
  'ORS': 'Yahari Ore no Seishun Love Comedy wa Machigatteiru',
  // Classiques
  'NS': 'Naruto Shippuden',
  'BLEACH': 'Bleach',
  'FT': 'Fairy Tail',
  'GT': 'Dragon Ball GT',
  'MF': 'Mahou Shoujo Madoka Magica',
  'PMMM': 'Mahou Shoujo Madoka Magica',
  'EF': 'Ergo Proxy',
  'EP': 'Ergo Proxy',
  'SY': 'Steins Gate',
  'SG': 'Steins Gate',
  'CC': 'Code Geass',
  'CG': 'Code Geass',
  'AKA': 'Akame ga Kill',
  'AGK': 'Akame ga Kill',
  'TFE': 'Fumetsu no Anata e',
  'BERSERK': 'Berserk',
  'GE': 'Gintama',
  'GT2': 'Gintama',
}
